### **IMPORT LIBRARY**

In [33]:
import pandas as pd
import numpy as np

### **PEMBACAAN DATA**

In [34]:
df = pd.read_csv("C:/Users/visco/IF-UNDIP/SEM 2/Statistika/LK2/Latihan.csv")

### **Properti #1:**

Menambah atau mengurangi dengan suatu nilai konstanta untuk semua dataset. Untuk menemukan properti pertama, kita akan mencari nilai mean (rata-rata) dan median (nilai tengah) dari kumpulan data, lalu menambahkan (atau mengurangi) suatu nilai konstanta yang sama untuk setiap baris dalam data, dan menemukan nilai rata-rata dan median yang baru.

**Langkah 1:**

Hitung nilai standard deviation dan variance sebelum memodifikasi dataset untuk
variabel Tipe3

In [35]:
df.head()

   Tipe1  Tipe2  Tipe3  Tipe4
0      5      5      4      2
1      5      3      2      3
2      5      4      2      3
3      5      3      2      2
4      4      3      2      4

In [36]:
#SEBELUM

print('=== Sebelum ===')
std_before = df['Tipe3'].std()
var_before = np.sqrt(std_before)
print(f'Standar deviasi Tipe3   : {std_before}')
print(f'Variansi Tipe3          : {var_before}')

=== Sebelum ===
Standar deviasi Tipe3   : 3.9046675366064867
Variansi Tipe3          : 1.976023161961035

**Langkah 2:**

Modifikasi satu buah variabel dari dataset terkait dengan menambahkan atau
mengurangi suatu konstanta untuk setiap data.

In [37]:
#SETELAH ditambah Konstanta
df1 = df.copy()

df1['Tipe3'] -= 8
df1.head()

   Tipe1  Tipe2  Tipe3  Tipe4
0      5      5     -4      2
1      5      3     -6      3
2      5      4     -6      3
3      5      3     -6      2
4      4      3     -6      4

**Langkah 3:**

Hitung nilai standard deviation dan variance dari modified dataset untuk melengkapi tabel pada Langkah 1 dan lakukan analisa terhadap hasil yang diperoleh sesuai pertanyaan berikut ini.

In [38]:
print('=== Setelah ===')
std_after = df1['Tipe3'].std()
var_after = np.sqrt(std_after)
print(f'Standar Deviasi Tipe3   : {std_after}')
print(f'Variansi Tipe3          : {var_after}')

=== Setelah ===
Standar Deviasi Tipe3   : 3.9046675366064867
Variansi Tipe3          : 1.976023161961035

### **Properti #2:**

Mengalikan atau membagi dengan suatu nilai konstanta untuk semua dataset.

**Langkah 1:**

Hitung nilai standard deviation dan variance sebelum memodifikasi dataset untuk
variabel Tipe2

In [39]:
df.head()

   Tipe1  Tipe2  Tipe3  Tipe4
0      5      5      4      2
1      5      3      2      3
2      5      4      2      3
3      5      3      2      2
4      4      3      2      4

In [40]:
#SEBELUM
print('=== Sebelum ===')
std_before = df['Tipe2'].std()
var_before = np.sqrt(std_before)
print(f'Standar Deviasi Tipe2   : {std_before}')
print(f'Median Tipe2            : {var_before}')

=== Sebelum ===
Standar Deviasi Tipe2   : 3.8048158137580557
Median Tipe2            : 1.9505937080176527

**Langkah 2:**

Modifikasi satu buah variabel dari dataset terkait dengan menambahkan suatu
konstanta untuk setiap data.

In [41]:
#SETELAH ditambah Konstanta
df2 = df.copy()

df2['Tipe2'] /= 4

df2.head()

   Tipe1  Tipe2  Tipe3  Tipe4
0      5   1.25      4      2
1      5   0.75      2      3
2      5   1.00      2      3
3      5   0.75      2      2
4      4   0.75      2      4

**Langkah 3:**

Hitung nilai mean dan median dari modified dataset untuk melengkapi tabel pada Langkah 1 dan lakukan analisa terhadap hasil yang diperoleh sesuai pertanyaan berikut ini.

In [42]:
print('=== Setelah ===')
std_after = df2['Tipe2'].std()
var_after = np.sqrt(std_after)
print(f'Standar Deviasi Tipe2   : {std_after}')
print(f'Median Tipe2            : {var_after}')

=== Setelah ===
Standar Deviasi Tipe2   : 0.9512039534395139
Median Tipe2            : 0.9752968540088264

### **Properti #3:**

Sensitif terhadap Outliers

**Langkah 1:**

Hitung nilai standard deviation dan variance sebelum memodifikasi dataset untuk
variabel Tipe4

In [43]:
df.head()

   Tipe1  Tipe2  Tipe3  Tipe4
0      5      5      4      2
1      5      3      2      3
2      5      4      2      3
3      5      3      2      2
4      4      3      2      4

In [44]:
#SEBELUM
print('=== Sebelum ===')
std_before = df['Tipe4'].std()
var_before = df['Tipe4'].var()
print(f'Standar Deviasi Tipe4   : {std_before}')
print(f'Variasi Tipe4: {var_before}')

=== Sebelum ===
Standar Deviasi Tipe4   : 1.869439807751294
Variasi Tipe4: 3.4948051948051946

**Langkah 2:**

Modifikasi dataset dengan menambahkan satu baris data.

In [45]:
df3 = df.copy()

# Tambah satu baris dengan nilai 1000
new_row = {'Tipe4': 1000}

df3 = pd.concat([df3, pd.DataFrame([new_row])], ignore_index=True)

df3.tail()

    Tipe1  Tipe2  Tipe3  Tipe4
52   15.0   10.0    8.0      2
53    4.0   20.0   12.0      5
54   15.0    6.0    5.0      4
55   20.0    5.0    3.0      6
56    NaN    NaN    NaN   1000

**Langkah 3:**

Hitung nilai standard deviation dan variance dari modified dataset untuk
melengkapi tabel pada Langkah 1 dan lakukan analisa terhadap hasil yang diperoleh sesuai
pertanyaan berikut ini.

In [46]:
print('=== Setelah ===')
std_after = df3['Tipe4'].std()
var_after = np.sqrt(std_after)
print(f'Mean   Tipe4: {std_after}')
print(f'Median Tipe4: {var_after}')

=== Setelah ===
Mean   Tipe4: 131.97900123473164
Median Tipe4: 11.488211402769869