### **IMPORT LIBRARY**

In [ ]:
import pandas as pd

### **PEMBACAAN DATA**

In [ ]:
df = pd.read_csv("LK2/Latihan.csv")

# Properti #1:

Menambah atau mengurangi dengan suatu nilai konstanta untuk semua dataset. Untuk menemukan properti pertama, kita akan mencari nilai mean (rata-rata) dan median (nilai tengah) dari kumpulan data, lalu menambahkan (atau mengurangi) suatu nilai konstanta yang sama untuk setiap baris dalam data, dan menemukan nilai rata-rata dan median yang baru.

Langkah 1:

Hitung nilai mean dan median sebelum memodifikasi dataset untuk
variabel Tipe3

In [65]:
df.head()

   Tipe1  Tipe2  Tipe3  Tipe4
0      5      5      4      2
1      5      3      2      3
2      5      4      2      3
3      5      3      2      2
4      4      3      2      4

In [66]:
#SEBELUM

print('=== Sebelum ===')
mean_before = df['Tipe3'].mean()
median_before = df['Tipe3'].median()
print(f'Mean   Tipe3: {mean_before}')
print(f'Median Tipe3: {median_before}')

=== Sebelum ===
Mean   Tipe3: 5.339285714285714
Median Tipe3: 4.0

Langkah 2:

Modifikasi satu buah variabel dari dataset terkait dengan menambahkan atau
mengurangi suatu konstanta untuk setiap data.

In [67]:
#SETELAH ditambah Konstanta
df1 = df.copy()

df1['Tipe3'] += 5
df1.head()

   Tipe1  Tipe2  Tipe3  Tipe4
0      5      5      9      2
1      5      3      7      3
2      5      4      7      3
3      5      3      7      2
4      4      3      7      4

Langkah 3:

Hitung nilai mean dan median dari modified dataset untuk melengkapi tabel pada Langkah 1 dan lakukan analisa terhadap hasil yang diperoleh sesuai pertanyaan berikut ini.

In [68]:
print('=== Setelah ===')
mean_after = df1['Tipe3'].mean()
median_after = df1['Tipe3'].median()
print(f'Mean   Tipe3: {mean_after}')
print(f'Median Tipe3: {median_after}')

=== Setelah ===
Mean   Tipe3: 10.339285714285714
Median Tipe3: 9.0

# Properti #2:

Mengalikan atau membagi dengan suatu nilai konstanta untuk semua dataset.

Langkah 1:

Hitung nilai mean dan median sebelum memodifikasi dataset untuk variabel Tipe2

In [69]:
df.head()

   Tipe1  Tipe2  Tipe3  Tipe4
0      5      5      4      2
1      5      3      2      3
2      5      4      2      3
3      5      3      2      2
4      4      3      2      4

In [70]:
#SEBELUM
print('=== Sebelum ===')
mean_before = df['Tipe2'].mean()
median_before = df['Tipe2'].median()
print(f'Mean   Tipe2: {mean_before}')
print(f'Median Tipe2: {median_before}')

=== Sebelum ===
Mean   Tipe2: 5.821428571428571
Median Tipe2: 5.0

Langkah 2: Modifikasi satu buah variabel dari dataset terkait dengan menambahkan suatu
konstanta untuk setiap data.

In [71]:
#SETELAH ditambah Konstanta
df2 = df.copy()

df2['Tipe2'] *= 3

df2.head()

   Tipe1  Tipe2  Tipe3  Tipe4
0      5     15      4      2
1      5      9      2      3
2      5     12      2      3
3      5      9      2      2
4      4      9      2      4

Langkah 3:

Hitung nilai mean dan median dari modified dataset untuk melengkapi tabel pada Langkah 1 dan lakukan analisa terhadap hasil yang diperoleh sesuai pertanyaan berikut ini.

In [72]:
print('=== Setelah ===')
mean_after = df2['Tipe2'].mean()
median_after = df2['Tipe2'].median()
print(f'Mean   Tipe2: {mean_after}')
print(f'Median Tipe2: {median_after}')

=== Setelah ===
Mean   Tipe2: 17.464285714285715
Median Tipe2: 15.0

# Properti #3:

Sensitif terhadap Outliers

Langkah 1:

Hitung nilai mean dan median sebelum memodifikasi dataset untuk variabel Tipe4

In [73]:
df.head()

   Tipe1  Tipe2  Tipe3  Tipe4
0      5      5      4      2
1      5      3      2      3
2      5      4      2      3
3      5      3      2      2
4      4      3      2      4

In [77]:
#SEBELUM
print('=== Sebelum ===')
mean_before = df['Tipe4'].mean()
median_before = df['Tipe4'].median()
print(f'Mean   Tipe4: {mean_before}')
print(f'Median Tipe4: {median_before}')

=== Sebelum ===
Mean   Tipe4: 3.6785714285714284
Median Tipe4: 3.5

Langkah 2: Modifikasi dataset dengan menambahkan satu baris data.

In [80]:
df3 = df.copy()

# Tambah satu baris dengan nilai 1000
new_row = {'Tipe4': 1000}

df3 = pd.concat([df3, pd.DataFrame([new_row])], ignore_index=True)

df3.tail()

    Tipe1  Tipe2  Tipe3  Tipe4
52   15.0   10.0    8.0      2
53    4.0   20.0   12.0      5
54   15.0    6.0    5.0      4
55   20.0    5.0    3.0      6
56    NaN    NaN    NaN   1000

Langkah 3: 

Hitung nilai mean dan median dari modified dataset untuk melengkapi tabel pada Langkah 1 dan lakukan analisa terhadap hasil yang diperoleh sesuai pertanyaan berikut ini.

In [82]:
print('=== Setelah ===')
mean_after = df3['Tipe4'].mean()
median_after = df3['Tipe4'].median()
print(f'Mean   Tipe4: {mean_after}')
print(f'Median Tipe4: {median_after}')

=== Setelah ===
Mean   Tipe4: 21.157894736842106
Median Tipe4: 4.0